---
apiVersion: v1
kind: Service
metadata:
  name: tweet-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: tweet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweet-deployment
  labels:
    app: tweet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweet
  template:
    metadata:
      labels:
        app: tweet
    spec:
      containers:
        - name: tweet
          image: microservice_tweet:1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URL
              value: mongodb://tweet-db:27017/tweet?replicaSet=rs0
            - name: WAIT_HOSTS
              value: tweet-db:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.5
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_URL
              value: redis://cache
